### ISSUE TITLE
Pre-trained models and scene objects

### ISSUE THREAD

**Issue by jiahao-z4568** [IGLICT/NeRF-Editing#1]
Hello, is it possible that the pre-trained models and scene objects to be shared? Thanks.

**Comment by nexuslrf** [comment]
+1 
Hi @FrozenSilent , this is an interesting work, it would be better if you could provide some demo models for us to directly play with. 😀

**Comment by FrozenSilent** [comment]
Thanks for your interest in our work!
We use [NeuS](https://github.com/Totoro97/NeuS) to extract the triangular mesh, and the training is not difficult.
We are preparing to release the pre-trained models and also some data and demo models for one to try easily.
Thanks for your suggestions!

**Comment by FrozenSilent** [comment]
Hello! Sorry for the late reply as I am working on other projects now.
We now provide a ready-to-use dataset along with the pre-trained model and intermediate results.
Now the code can also be trained on the nerf-synthetic dataset, hope that helps!
More details are included in ReadMe.
If you still have problems, welcome to open the issue!
