### ISSUE TITLE
Compilation environment

### ISSUE THREAD

**Issue by hanbiao3906** [IGLICT/NeRF-Editing#4]
Hello, author
I want to ask, what is your development environment? I tried to run your project with pycharm, but failed.
I see that your project references jitter and some of its C++packages, so I'm very confused about what development tools you use?

**Comment by FrozenSilent** [comment]
We tested the code on ubuntu 18.04, python 3.7. For Python, Pycharm is a suitable IDE. For C++, Visual Studio is a good choice.

**Comment by hanbiao3906** [comment]
Thank you.
