### ISSUE TITLE
How to train on our own dataset?

### ISSUE THREAD

**Issue by rockywind** [IGLICT/NeRF-Editing#5]
Hi,
My datasets consisted of the image, point cloud, and camera pose. How can I transfer my dataset to a trainable dataset?
My dataset is autonumous driving scene, such as kitti.

**Comment by FrozenSilent** [comment]
The input data structure has been shown in the README file. In fact, only three parts are used, `pose`, `rgb`, and `intrinsics.txt`. You only need to prepare these three parts before training.
