### ISSUE TITLE
GT Edited mesh

### ISSUE THREAD

**Issue by jiyoonshincml** [IGLICT/NeRF-Editing#6]
Hi, thanks for sharing the great work!

I'm curious how you extracted the GT edited meshes that are shown in your paper.

Using blender, I cant find a way to extract an edited mesh including color. 
After some edits and using export, I can only export meshes NOT including any color (in gray).

Maybe I'm missing something.. but I can never find the way.

Thanks!

**Comment by jiyoonshincml** [comment]
Following your work again... it seems that you used the rendered image (in blender, render->render image)  as the ground truth, not extracting a colored mesh and rendering views; is that right ?

**Comment by FrozenSilent** [comment]
Hi! Thanks for your interest in our work!
1. The color of the mesh extracted from NeuS is the vertex color. If the exported mesh from Blender does not have colors, the vertex color of the original mesh can be directly used.
2. The ground truth images used in training come from [NeRF-Synthetic dataset](https://drive.google.com/drive/folders/128yBriW1IG_3NJ5Rp7APSTZsJqdJdfc1) and these should come from the original model. And the rendered images in the result section were obtained by rendering the reconstructed model.

**Comment by jiyoonshincml** [comment]
Thank you!
